---
# tasks file for prometheus-mysql-exporter
#
- name: mysql_exporter group
  group:
      name: '{{ prometheus_mysql_exporter_group }}'
      state: present
      system: true

- name: mysql_exporter user
  user:
      name: '{{ prometheus_mysql_exporter_user }}'
      state: present
      system: true
      home: '{{ prometheus_mysql_exporter_basedir }}'
      shell: '/sbin/nologin'

- name: mysql_exporter archive download
  get_url:
      url: '{{ prometheus_mysql_exporter_dl }}'
      dest: '/tmp/mysql_exporter-{{ prometheus_mysql_exporter_version }}/{{ prometheus_mysql_exporter_os }}-{{ prometheus_mysql_exporter_arch }}.tar.gz'
      checksum: 'sha256: {{ prometheus_mysql_exporter_checksum }}'

- name: mysql_exporter extract
  unarchive:
      src: '/tmp/mysql_exporter-{{ prometheus_mysql_exporter_version }}/{{ prometheus_mysql_exporter_os }}-{{ prometheus_mysql_exporter_arch }}.tar.gz'
      dest: '{{ prometheus_mysql_exporter_basedir }}'
